# Site Settings
title: Scott Walmsley, PhD
url: ''
baseurl: '' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Scott Walmsley, PhD
tagline: Big data scientist, bioinformaticist and molecular biologist
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Originally a bench scientist in the field of molecular biology, I have developed skills to answer difficult questions of disease and biomarker discovery through computer code.
My career has co-evolved with the challenges of mass spectrometry based and clinical data analysis. 
<br><br>
<h5><i>I am currently seeking a position as a Data Scientist, Bioinformatics Scientist or Computational Scientist at the mid to senior level.</i></h5>
<br><br><i>Click on sub titles below to expand.</i>"

#sidebar links
email: walmslsj89@gmail.com
phone: +1 970-691-2060
website: scottwalmsley.github.io #do not add http://
linkedin: scott-walmsley-3a95447
github: scottwalmsley
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: #UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
